### PR TITLE
Add Nix Flake

### PR DESCRIPTION
**Pull request by justDeeevin**
This allows NixOS users to install and use Syspower, as well as providing options for configuring the app with Nix via Home Manager.

I'm currently successfully using this flake to run and configure syspower on my computer.

### CODE REVIEW

**Comment by System64fumo** [comment]
A few of my programs exist on the nix package manager already. (package maintained by other people)
I was not asked to add anything to my repos, Is such change necessary?

**Comment by justDeeevin** [comment]
**It is not necessary to add anything to this repo to get the app onto nixpkgs**. The Flake allows users to install the software _without_ it being on nixpkgs. If you don't want to add it, I understand. I can look into getting syspower onto nixpkgs instead.

**Comment by justDeeevin** [comment]
I decided to go this route instead of attempting to put it on nixpkgs because it allows me to more quickly use it on my system (i don't have to wait for a PR to get merged into nixpkgs master then get backported to unstable). Also because there isn't yet a release version of this app.

**Comment by System64fumo** [comment]
I would prefer to keep package manager specific things out of the main repo.

I don't mind making changes to make my programs compatible with other package managers or distributions though.

Thank you for understanding.

**Comment by justDeeevin** [comment]
Gotcha!

**Comment by System64fumo** [comment]
Regarding easier and faster usage, I can see why such change would be nice to have however this program is so simple it rarely gets any updates. (A few are planned in the very near future)

And regarding a stable release that won't happen as i don't quite believe in release versions of software.

**Pull request closed without merging**
